org: orgDemo
app: appDemo
stage: dev
component: postgresql
name: postgresqlDemo

inputs:
  region: ap-guangzhou
  zone: ap-guangzhou-2
  dBInstanceName: postgresqlDemo
  vpcConfig:
    vpcId: vpc-b6531flb
    subnetId: subnet-eexos4wi
  extranetAccess: true
